---
- name: install packages
  apt:
    name: '{{ item }}'
    state: present
    update_cache: yes
  loop:
    - ufw
    - nginx
    - letsencrypt

- name: create nginx config
  copy:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf

- name: remove nginx default site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: restart nginx service
  systemd:
    name: nginx
    state: restarted
    daemon_reload: yes
    enabled: yes
  changed_when: false

# - name: Enable firewall
#   ufw:
#     state: enabled

- name: create letsencrypt directory
  file:
    name: /var/www/letsencrypt
    state: directory

- name: copy journald config
  copy:
    src: journald.conf
    dest: /etc/systemd/journald.conf

- name: restart journald
  systemd:
    name: systemd-journald
    state: restarted
    daemon_reload: yes
    enabled: yes
  changed_when: false