---

- hosts: all
  become: true
  tasks: 
  
  - name: install MariaDb server
    tags: ubuntu,mariadb
    package:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

