---

- hosts: all
  become: true
  tasks: 
  
  - name: install MariaDb server
    tags: ubuntu,mariadb
    package:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install unzip
    tags: unzip
    package: 
      name: unzip

  - name: install terraform
    unarchive:
      src: https://releases.hashicorp.com/terraform/0.12.28/terraform_0.12.28_linux_amd64.zip
      dest: /usr/local/bin
      remote_src: yes
      mode: 0755
      owner: root
      group: root

  - name: copy file to server
    tags: ubuntu,mariadb
    copy:
      src: README.md
      dest: /var/www/html/
      owner: root
      group: root
      mode: 0644
    when: ansible_distribution == "Ubuntu"

